# Format of the whole prompt
format = '$username - \[$directory\] $git_branch$git_commit$git_state$git_metrics$git_status$all'

# Symbol to display before the commands
[character]
success_symbol = "[λ >](bold green)"
error_symbol = "[✘ >](bold red)"

# Username display
[username]
style_user = "blue bold italic"
format = '[$user]($style)'
disabled = false
show_always = true

# Working directory display
[directory]
style = "bold green"
format = '[$path]($style)[$read_only]($read_only_style)'

# Kinda a hack to display a "right prompt"
[fill]
symbol = " "

[package]
disabled = true

[c]
detect_files = ["Makefile"]
symbol = "c "
format = "via [$symbol]($style)"

[cmd_duration]
disabled = true

# Text language symbols
[aws]
symbol = "aws "
format = "via [$symbol]($style)"

[bun]
symbol = "bun "
format = "via [$symbol]($style)"

[cobol]
symbol = "cobol "
format = "via [$symbol]($style)"

[conda]
symbol = "conda "
format = "via [$symbol]($style)"

[crystal]
symbol = "cr "
format = "via [$symbol]($style)"

[cmake]
symbol = "cmake "
format = "via [$symbol]($style)"

[daml]
symbol = "daml "
format = "via [$symbol]($style)"

[dart]
symbol = "dart "
format = "via [$symbol]($style)"

[deno]
symbol = "deno "
format = "via [$symbol]($style)"

[dotnet]
symbol = ".NET "
format = "via [$symbol]($style)"

[docker_context]
symbol = "docker "
format = "via [$symbol]($style)"

[elixir]
symbol = "exs "
format = "via [$symbol]($style)"

[elm]
symbol = "elm "
format = "via [$symbol]($style)"

[golang]
symbol = "go "
format = "via [$symbol]($style)"

[java]
symbol = "java "
format = "via [$symbol]($style)"

[julia]
symbol = "jl "
format = "via [$symbol]($style)"

[kotlin]
symbol = "kt "
format = "via [$symbol]($style)"

[lua]
symbol = "lua "
format = "via [$symbol]($style)"

[nodejs]
symbol = "nodejs "
format = "via [$symbol]($style)"

[meson]
symbol = "meson "
format = "via [$symbol]($style)"

[nim]
symbol = "nim "
format = "via [$symbol]($style)"

[ocaml]
symbol = "ml "
format = 'via [$symbol(\($switch_indicator$switch_name\) )]($style)'

[opa]
symbol = "opa "
format = "via [$symbol]($style)"

[os.symbols]
Alpine = "alp "
Amazon = "amz "
Android = "andr "
Arch = "rch "
CentOS = "cent "
Debian = "deb "
DragonFly = "dfbsd "
Emscripten = "emsc "
EndeavourOS = "ndev "
Fedora = "fed "
FreeBSD = "fbsd "
Garuda = "garu "
Gentoo = "gent "
HardenedBSD = "hbsd "
Illumos = "lum "
Linux = "lnx "
Macos = "mac "
Manjaro = "mjo "
Mariner = "mrn "
MidnightBSD = "mid "
Mint = "mint "
NetBSD = "nbsd "
NixOS = "nix "
OpenBSD = "obsd "
openSUSE = "osuse "
OracleLinux = "orac "
Pop = "pop "
Raspbian = "rasp "
Redhat = "rhl "
RedHatEnterprise = "rhel "
Redox = "redox "
Solus = "sol "
SUSE = "suse "
Ubuntu = "ubnt "
Unknown = "unk "
Windows = "win "

[perl]
symbol = "pl "
format = "via [$symbol]($style)"

[php]
symbol = "php "
format = "via [$symbol]($style)"

[pulumi]
symbol = "pulumi "
format = "via [$symbol]($style)"

[purescript]
symbol = "purs "
format = "via [$symbol]($style)"

[python]
symbol = "py "
format = "via [$symbol]($style)"

[raku]
symbol = "raku "
format = "via [$symbol]($style)"

[ruby]
symbol = "rb "
format = "via [$symbol]($style)"

[rust]
symbol = "rs "
format = "via [$symbol]($style)"

[scala]
symbol = "scala "
format = "via [$symbol]($style)"

[spack]
symbol = "spack "
format = "via [$symbol]($style)"

[sudo]
symbol = "sudo "

[swift]
symbol = "swift "
format = "via [$symbol]($style)"

[terraform]
symbol = "terraform "

[zig]
symbol = "zig "
format = "via [$symbol]($style)"
