# Format of the whole prompt
format = '$username - \[$directory\] $git_branch$git_commit$git_state$git_metrics$git_status$fill$all'

# Don't add a new line before a prompt
add_newline = false

# Symbol to display before the commands
[character]
success_symbol = "[λ >](bold green)"
error_symbol = "[λ >](bold red)"

# Username display
[username]
style_user = "cyan bold"
format = '[$user]($style)'
disabled = false
show_always = true

# Working directory display
[directory]
style = "bold green"
format = '[$path]($style)[$read_only]($read_only_style)'

# Kinda a hack to display a "right prompt"
[fill]
symbol = " "

[package]
format = "[$symbol$version]($style) "

[c]
detect_files = ["Makefile"]

[cmd_duration]
disabled = true