#! /usr/bin/env sh

# Reset all rules
bspc rule -r "*"

pgrep -x sxhkd > /dev/null || sxhkd &

# Set workspace
bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Gaps and border
bspc config border_width         4
bspc config window_gap          15

# General behaviour
bspc config split_ratio          	0.5
bspc config borderless_monocle   	true
bspc config gapless_monocle      	true
bspc config single_monocle 	 	false
bspc config focus_follows_pointer	true

# Colors
bspc config focused_border_color	"#C792EA"
bspc config normal_border_color		"#292D3E"
bspc config active_border_color		"#89DDFF"

# Don't focus workspace when app opens
bspc config ignore_ewmh_focus true

# Assign apps to workspaces
bspc rule -a Alacritty desktop='^1' state=tiled follow=on focus=on
bspc rule -a firefox desktop='^2' state=tiled follow=off focus=off
bspc rule -a code-oss desktop='^3' state=tiled follow=off focus=off
bspc rule -a obsidian desktop='^4' state=tiled follow=off focus=off

# Startup apps
alacritty &
firefox &
code &
obsidian &

# Notification daemon
dunst &

# Bar
polybar base &

# Wallpaper
feh --bg-scale /usr/share/backgrounds/wallpaper.png &

xsetroot -cursor_name left_ptr

# Keypress rate
xset r rate 300 30

# Emacs tiled mode
bspc rule -a "Emacs" state=tiled

# Start emacs server
emacs --daemon
